### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Omerrit** [DOG729/ruMount-BladeBannerlord#188]
Здравствуйте! В  readme указано, что нужно заменить Modules, но при установке игры в день написание issue в Modules установлена папка Native, которая содержит файлы игры (40 gb), подозреваю, что заменив Modules, игра не сможет запуститься, не понимаю, что делать в этой ситуации, можете помочь в моей ситуации или обновить readme ?
![Modules](https://user-images.githubusercontent.com/45018148/79039629-45650200-7beb-11ea-8c69-d78779c4798b.PNG)

**Comment by taranikys** [comment]
Русификатор устанавливается модулем, если вам будет проще, то папку Russian, в папку Modules
